/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SchemaCompileRequest } from '../../models/schema-compile-request';
import { SchemaCompileResponse } from '../../models/schema-compile-response';

export interface CompileDbSchema$Params {
      body: SchemaCompileRequest
}

export function compileDbSchema(http: HttpClient, rootUrl: string, params: CompileDbSchema$Params, context?: HttpContext): Observable<StrictHttpResponse<SchemaCompileResponse>> {
  const rb = new RequestBuilder(rootUrl, compileDbSchema.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SchemaCompileResponse>;
    })
  );
}

compileDbSchema.PATH = '/api/compile/schema';
