/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CompileRequest } from '../../models/compile-request';
import { CompileResponse } from '../../models/compile-response';

export interface CompileDbObject$Params {
      body: CompileRequest
}

export function compileDbObject(http: HttpClient, rootUrl: string, params: CompileDbObject$Params, context?: HttpContext): Observable<StrictHttpResponse<CompileResponse>> {
  const rb = new RequestBuilder(rootUrl, compileDbObject.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CompileResponse>;
    })
  );
}

compileDbObject.PATH = '/api/compile';
