/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DbObjectsResponse } from '../../models/db-objects-response';

export interface ListDbObjects$Params {
  env: string;
  schema: string;
  object_type: string;
}

export function listDbObjects(http: HttpClient, rootUrl: string, params: ListDbObjects$Params, context?: HttpContext): Observable<StrictHttpResponse<DbObjectsResponse>> {
  const rb = new RequestBuilder(rootUrl, listDbObjects.PATH, 'get');
  if (params) {
    rb.query('env', params.env, {});
    rb.query('schema', params.schema, {});
    rb.query('object_type', params.object_type, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DbObjectsResponse>;
    })
  );
}

listDbObjects.PATH = '/api/db/objects';
