/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DateColumnsResponse } from '../../models/date-columns-response';

export interface ListDbDateColumns$Params {
  env: string;
  schema: string;
  table: string;
}

export function listDbDateColumns(http: HttpClient, rootUrl: string, params: ListDbDateColumns$Params, context?: HttpContext): Observable<StrictHttpResponse<DateColumnsResponse>> {
  const rb = new RequestBuilder(rootUrl, listDbDateColumns.PATH, 'get');
  if (params) {
    rb.query('env', params.env, {});
    rb.query('schema', params.schema, {});
    rb.query('table', params.table, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DateColumnsResponse>;
    })
  );
}

listDbDateColumns.PATH = '/api/db/date-columns';
