/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SchemasResponse } from '../../models/schemas-response';

export interface ListDbSchemas$Params {
  env: string;
}

export function listDbSchemas(http: HttpClient, rootUrl: string, params: ListDbSchemas$Params, context?: HttpContext): Observable<StrictHttpResponse<SchemasResponse>> {
  const rb = new RequestBuilder(rootUrl, listDbSchemas.PATH, 'get');
  if (params) {
    rb.query('env', params.env, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SchemasResponse>;
    })
  );
}

listDbSchemas.PATH = '/api/db/schemas';
