/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MigrationRequest } from '../../models/migration-request';
import { MigrationResponse } from '../../models/migration-response';

export interface MigrateDbData$Params {
      body: MigrationRequest
}

export function migrateDbData(http: HttpClient, rootUrl: string, params: MigrateDbData$Params, context?: HttpContext): Observable<StrictHttpResponse<MigrationResponse>> {
  const rb = new RequestBuilder(rootUrl, migrateDbData.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MigrationResponse>;
    })
  );
}

migrateDbData.PATH = '/api/migrate';
