/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { QueryRequest } from '../../models/query-request';
import { QueryResponse } from '../../models/query-response';

export interface QueryDb$Params {
      body: QueryRequest
}

export function queryDb(http: HttpClient, rootUrl: string, params: QueryDb$Params, context?: HttpContext): Observable<StrictHttpResponse<QueryResponse>> {
  const rb = new RequestBuilder(rootUrl, queryDb.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<QueryResponse>;
    })
  );
}

queryDb.PATH = '/api/query';
