/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SessionItemInfo } from '../../models/session-item-info';
import { UpdateSessionItemRequest } from '../../models/update-session-item-request';

export interface CreateSessionItem$Params {
  session_id: string;
      body: UpdateSessionItemRequest
}

export function createSessionItem(http: HttpClient, rootUrl: string, params: CreateSessionItem$Params, context?: HttpContext): Observable<StrictHttpResponse<SessionItemInfo>> {
  const rb = new RequestBuilder(rootUrl, createSessionItem.PATH, 'post');
  if (params) {
    rb.path('session_id', params.session_id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SessionItemInfo>;
    })
  );
}

createSessionItem.PATH = '/api/sessions/{session_id}/items/create';
