/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ReadParamsEntry } from '../models/read-params-entry';
export interface BodyParamsRead {
  entries: Array<(ReadParamsEntry | string)>;
  envs: Array<string>;
}
