/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * The generated script. Compiling never writes: the caller decides whether
 * and when to send ``script`` to ``/api/execute/sql``.
 */
export interface CompileResponse {
  code_a?: (string | null);
  code_b?: (string | null);
  env_a: string;
  env_b: string;
  notes?: Array<string>;
  object_name: string;
  object_type: string;
  schema_name: string;
  script?: (string | null);
  status: string;
}
