/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Compile an object from one environment into another (origen -> destino).
 */
export interface CompileRequest {
  env_a: string;
  env_b: string;
  object_name: string;
  object_type: string;
  schema_name: string;
}
