/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DateColumnInfo } from '../models/date-column-info';

/**
 * The columns a window can be built on, so the picker is not guesswork.
 */
export interface DateColumnsResponse {
  columns?: Array<DateColumnInfo>;
  env: string;
  schema_name: string;
  table_name: string;
}
