/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * The tables or stored procedures of one schema, to feed the object picker.
 *
 * Named ``schema_name`` like every other model of this contract: ``schema``
 * would shadow the deprecated ``BaseModel.schema`` and warn on import.
 */
export interface DbObjectsResponse {
  env: string;
  object_type: string;
  objects?: Array<string>;
  schema_name: string;
}
