/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * One environment. Every field is optional because the chain can stop at any step.
 */
export interface DeploymentEnvInfo {
  branch?: (string | null);
  branch_from_pipeline?: (number | null);
  commit?: (string | null);
  commit_subject?: (string | null);
  env: string;
  image?: (string | null);
  message?: (string | null);
  pipeline_id?: (number | null);
  pipeline_url?: (string | null);
  region?: (string | null);
  source_pipeline_id?: (number | null);

  /**
   * ok | not_applicable | no_task_definition | no_container | no_pipeline_id | circleci_unavailable | bitbucket_unavailable | error
   */
  status: string;
  tag?: (string | null);
  task_definition_family?: (string | null);
  task_definition_revision?: (number | null);
}
