/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DeploymentsBranchesRequest {

  /**
   * Ambientes a consultar. Vacío o ausente = todos los que estén en la configuración. Es lo que hace que mirar una región no cueste el viaje a las otras.
   */
  envs?: (Array<string> | null);

  /**
   * Nombre del repo en Bitbucket, sin el workspace. Ej: yappy-trnxd-backend-payment-aggregator
   */
  repo: string;
}
