/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MigrationRequest {
  code: string;
  confirm?: boolean;
  default_schema?: string;
  dry_run?: boolean;
  env_a: string;
  env_b: string;
}
