/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * One table of a migration.
 *
 * The source table is reported as ``schema``/``table`` rather than
 * ``schema_name``/``table_name`` to keep it aligned with the SQL projection it
 * came from.
 */
export interface MigrationTableInfo {
  alias: string;
  error?: (string | null);
  ok?: boolean;
  replaced?: number;
  row_count?: number;
  schema_name: string;
  select_sql: string;
  skipped_columns?: Array<string>;
  table_name: string;
  target_schema: string;
  target_table: string;
}
