/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ReadEntryResultInfo } from '../models/read-entry-result-info';
export interface ParamsReadResponse {
  envs?: Array<string>;
  err_count: number;
  ok_count: number;
  results: Array<ReadEntryResultInfo>;
}
