/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface QueryResponse {
  columns?: Array<string>;
  env: string;
  ms?: number;
  rows?: Array<{
[key: string]: any;
}>;
  total?: (number | null);
  truncated?: boolean;
}
