/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Compile a whole schema from one environment into another (origen -> destino).
 *
 * The bulk sibling of ``CompileRequest``: one script for every table and stored
 * procedure the origin has in that schema, ordered so MySQL accepts it. Both
 * flags default to ``True`` because "sync this schema" means the schema; the
 * flags exist to narrow the scope, and at least one of them must be on.
 */
export interface SchemaCompileRequest {
  env_a: string;
  env_b: string;
  include_procedures?: boolean;
  include_tables?: boolean;
  schema_name: string;
}
