/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Compile a whole schema from one environment into another (origen -> destino).
 *
 * The bulk sibling of ``CompileRequest``: one script for every table and stored
 * procedure the origin has in that schema, ordered so MySQL accepts it.
 *
 * The scope is one of three shapes, in this order:
 *
 * 1. ``tables``/``procedures`` carry an explicit list, because the browser
 *    showed the user a table with a checkbox per object and they chose. An
 *    explicit list is the whole scope: the two flags below are ignored, since
 *    they would only widen or narrow what the user just picked.
 * 2. Otherwise the two flags apply, and both default to ``True`` because "sync
 *    this schema" means the schema. They exist for a client with no table to
 *    show, and at least one of them must be on.
 * 3. An explicit list that is empty is a scope of nothing, which the route
 *    rejects — it is different from "not given", and reading it as "everything"
 *    would compile the whole schema the user had just emptied on purpose.
 */
export interface SchemaCompileRequest {
  env_a: string;
  env_b: string;
  include_procedures?: boolean;
  include_tables?: boolean;
  procedures?: (Array<string> | null);
  schema_name: string;
  tables?: (Array<string> | null);
}
