/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * One script for the whole schema. Compiling never writes: the caller decides
 * whether and when to send ``script`` to ``/api/execute/sql``.
 *
 * ``left_alone`` is the answer to "what happens to the tables that are only in
 * the destination": nothing. They are reported so the user sees them before
 * running the script, and they never appear in it.
 */
export interface SchemaCompileResponse {
  create_schema: boolean;
  env_a: string;
  env_b: string;
  left_alone?: Array<string>;
  notes?: Array<string>;
  procedures?: Array<string>;
  schema_name: string;
  script: string;
  status: string;
  tables?: Array<string>;
}
