/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * One table of a table-list migration and the window to take from it.
 *
 * ``date_from``/``date_to`` are inclusive dates, as the person filling the form
 * reads them; the half-open bounds they are rendered as are the library's
 * business. A ``date_column`` with no dates migrates the whole table, which is
 * also what omitting the column does.
 */
export interface TableSelectionRequest {
  date_column?: (string | null);
  date_from?: (string | null);
  date_to?: (string | null);
  table: string;
}
