/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TableSelectionRequest } from '../models/table-selection-request';

/**
 * Migrate an explicit list of tables of one schema (origen -> destino).
 *
 * The bulk sibling of ``MigrationRequest``: same engine, same response model, and
 * the source of each ``SELECT`` is this list instead of a user-written query.
 */
export interface TableMigrateRequest {
  confirm?: boolean;
  dry_run?: boolean;
  env_a: string;
  env_b: string;
  schema_name: string;
  tables: Array<TableSelectionRequest>;
}
